## Лабораторная работа №1 | Вариант 6

Выполнил: Мамонтов Егор Олегович М8О-312Б-22

### 1. Numpy

In [3]:
import numpy as np

1. Создайте единичную матрицу размером 3х3

In [4]:
matrix1 = np.eye(3)
print(matrix1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Создайте матрицу 5х5 со значениями 1, 2, 3, 4 ниже диагонали

In [5]:
matrix2 = np.array([[0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0]])
print(matrix2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


3. Какой выход будет у данного скрипта

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [6]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

9
10


4. Как найти самое часто встречаемое значение между двумя массивами? 

In [7]:
arr1 = np.array([3, 4, 3, 2])
arr2 = np.array([1, 4, 3, 3])

arr12 = np.concatenate([arr1, arr2])
counts = np.bincount(arr12)
print(np.argmax(counts))

3


5. Как игнорировать все warnings в numpy(не нужно так делать, но покажи)?

In [97]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

6. Реализуем функцию-генератор, которая генерирует 10 целых чисел и используем ее для построения массива

In [92]:
def intGenerator (array):
    for i in range (10):
        array.append(np.random.randint(0, 100))

array = [0.0]

7. Создайте массив случайных чисел размером 10 и отсортируйте его

In [93]:
intGenerator(array)
print(array)

print(np.sort(array))

[0.0, 46, 86, 55, 77, 52, 78, 87, 61, 39, 22]
[ 0. 22. 39. 46. 52. 55. 61. 77. 78. 86. 87.]


8. Создайте случайную матрицу 10х2 которая представляет собой декартовые координаты и преобразуйте их в полярные

In [77]:
x_arr = [0.0]
y_arr = [0.0]
p = 0.0
intGenerator(x_arr)
intGenerator(y_arr)

array2d = np.array([x_arr, y_arr])
print(array2d)

for i in range (10):
    p = np.sqrt(np.square(x_arr[i]) + np.square(y_arr[i]))
    phi = np.arccos(x_arr[i] / p)
    array2d[0][i] = p
    array2d[1][i] = phi

print("----------------------")
array2d

[[ 0.  7. 49. 17. 90. 35. 57. 11.  1. 60. 71.]
 [ 0. 74. 80. 49. 46.  0. 72. 92. 63. 64. 23.]]
----------------------


array([[  0.        ,  74.33034374,  93.81364506,  51.86520992,
        101.07423015,  35.        ,  91.83136719,  92.65527508,
         63.00793601,  87.7268488 ,  71.        ],
       [         nan,   1.47648238,   1.02123631,   1.23685125,
          0.47249694,   0.        ,   0.90115738,   1.45179603,
          1.55492464,   0.81764505,  23.        ]])

9. Создайте структурированный массив который будет описывать пиксель(координату x, y и цвет r,g,b)

In [ ]:
struct_arr = np.array[["x"],["y"],["r"],["g"],["b"]]

10. Как конвертировать тип массив от float32 в int32 in place?

In [79]:
int_arr = np.random.random((10))
print(int_arr)
int_arr.astype("int32")

[0.88864748 0.47362801 0.46604493 0.85422514 0.67366945 0.4568467
 0.30421386 0.30041734 0.24720321 0.37339495]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Набор данных описывает эффективность учеников в зависимости от некоторых факторов влияющих на обучение и окружение человека.

Файл: `student_perfomance.csv`

```
Hours_Studied - количество часов затраченное на обучение в неделю
Attendance - поцент посещенных занятий
Parental_Involvement - уровень участия родителей в обучении учащегося
Access_to_Resources - доступность ресурсов для обучения
Extracurricular_Activities - участие во внеклассных мероприятиях
Sleep_Hours - количество часов выделяемое на сон в день
Previous_Scores - оценка за первый экзамен
Motivation_Level - уровень мотивации
Internet_Access - доступ к интернету
Tutoring_Sessions - количество посещаемых репетиторских занятий в месяц.
Family_Income - доход семьи
Teacher_Quality - насколько качественно преподает учитель
School_Type - тип школы(частная, обычная)
Peer_Influence - влияние сверстников
Physical_Activity - физическая активность
Learning_Disabilities - наличие проблем с обучаемостью
Parental_Education_Level - уровень образования родителей
Distance_from_Home - дистанция от дома до школы
Gender - пол
Exam_Score - оценка на конечном экзамене
```

In [83]:
import pandas as pd

In [84]:
data = pd.read_csv('student_perfomance.csv')

1. Посчитайте среднее кол-во часов уделяемое на сон студентами

In [87]:
arr = np.zeros((6607))

for i in range(0, 6607):
    arr[i] = data.at[i, 'Sleep_Hours']

print(np.average(arr))

7.029060087785682


2. Сколько процентов студентов посещают внеклассовые активности?

In [90]:
c = 0
for i in range(0, 6607):
    if data.at[i, 'Extracurricular_Activities'] == "Yes":
        c += 1
print(c / 6607 * 100)


59.60345088542455


3. Правда ли, что в среднем девушки сдают экзамены лучше, чем мужчины

In [102]:
arr_male = np.zeros((6607))
arr_female = np.zeros((6607))

for i in range(0, 6607):
    if data.at[i, 'Gender'] == "Male":
        arr_male[i] = data.at[i, 'Exam_Score']
    if data.at[i, 'Gender'] == "Female":
        arr_female[i] = data.at[i, 'Exam_Score']

if np.average(arr_female) > np.average(arr_male):
    print(True)
else:
    print(False)

False


4. Выведите 25 и 75 перцентили времени сна студентов

In [110]:
data.describe(percentiles=[0.25, 0.75])

Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000   
mean       19.975329    79.977448      7.02906        75.070531   
std         5.990594    11.547475      1.46812        14.399784   
min         1.000000    60.000000      4.00000        50.000000   
25%        16.000000    70.000000      6.00000        63.000000   
50%        20.000000    80.000000      7.00000        75.000000   
75%        24.000000    90.000000      8.00000        88.000000   
max        44.000000   100.000000     10.00000       100.000000   

       Tutoring_Sessions  Physical_Activity   Exam_Score  
count        6607.000000        6607.000000  6607.000000  
mean            1.493719           2.967610    67.235659  
std             1.230570           1.031231     3.890456  
min             0.000000           0.000000    55.000000  
25%             1.000000           2.000000    65.000000  
50%             1.000000           3.000000    67.000000  
75%             2.000000           4.000000    69.000000  
max             8.000000           6.000000   101.000000

5. Правда ли, что те, кто спит больше(75 перцентиль и выше) сдает экзамен лучше, чем студенты с недосыпом(25 перцентиль и меньше)

In [114]:
per_25 = data['Sleep_Hours'].quantile(0.25)
per_75 = data['Sleep_Hours'].quantile(0.75)

arr_25 = np.zeros((6607))
arr_75 = np.zeros((6607))

for i in range(0, 6607):
    if data.at[i, 'Sleep_Hours'] <= data['Sleep_Hours'].quantile(0.25):
        arr_25[i] = data.at[i, 'Exam_Score']
    if data.at[i, 'Sleep_Hours'] >= data['Sleep_Hours'].quantile(0.75):
        arr_75[i] = data.at[i, 'Exam_Score']

if np.average(arr_25) < np.average(arr_75):
    print(True)
else:
    print(False)

True


6. Влияет ли физическая активность на результаты экзамена?

In [150]:
pd.crosstab(data["Physical_Activity"], data["Exam_Score"])
for i in range(6):
    print(i)
    print(data[data["Physical_Activity"] == i]["Exam_Score"].mean())

0
67.52173913043478
1
66.96912114014252
2
67.18500307314075
3
67.19607072691552
4
67.31301587301587
5
67.6038781163435


7. Правда ли, что слуденты, чьи родители имеют высшее образование, сдают экзамены лучше, чем остальные?

In [121]:
arr_grade = np.zeros((6607))
arr_degrade = np.zeros((6607))

for i in range(0, 6607):
    if data.at[i, 'Parental_Education_Level'] == "Postgraduate":
        arr_grade[i] = data.at[i, 'Exam_Score']
    else:
        arr_degrade[i] = data.at[i, 'Exam_Score']

if np.average(arr_grade) > np.average(arr_degrade):
    print(True)
else:
    print(False)

False


8. Как влияет участие родителей на результаты экзаменов

In [163]:
pd.crosstab(data["Parental_Involvement"], data["Exam_Score"])
d = {"Low": 0, "Medium": 1, "High": 2}
for i in range(3):
    print(i)
    print(
        data[
            data["Parental_Involvement"].map(d) == i
            ]
            ["Exam_Score"].mean()
        )

0
66.35826477187734
1
67.09815585960737
2
68.09276729559748


9. Правда ли, что в семьях с доходом больше среднего дети сдают экзамены лучше?

In [124]:
arr_high = np.zeros((6607))
arr_low = np.zeros((6607))

for i in range(0, 6607):
    if data.at[i, 'Family_Income'] == "High":
        arr_high[i] = data.at[i, 'Exam_Score']
    else:
        arr_low[i] = data.at[i, 'Exam_Score']

if np.average(arr_high) > np.average(arr_low):
    print(True)
else:
    print(False)

False


10. Посчитайте долю студентов сдавших экзамен на более чем 70 баллов в семьях с доходом ниже 25го перцентиля и отсутствием доступа к интернету

In [130]:
no_rich_smart = 0
d = {"Low": 0, "Medium": 1, "High": 2}
for i in range (6607):
    if data.at[i, 'Exam_Score'] >= 70:

        if d[data.at[i, 'Family_Income']] <= data['Family_Income'].map(d).quantile(0.25):
            if data.at[i, 'Internet_Access'] == "No":
                no_rich_smart += 1
print(no_rich_smart / 6607 * 100)

0.39352202209777504


### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Правда ли, что количество часов затрачиваемых на сон распределено примерно нормально?

In [ ]:
import matplotlib as mp
import seaborn as sns
import plotly as pt
import pandas as pd

2. Постройте гистограмму распределения количества часов затрачиваемых на обучение среди мальчиков и девочек

3. Как зависит результат конечного экзамена от результата первого экзамена

4. Постройте box plot отображающий распределение доходов семей детей сдавших экзамены на оценку ниже и выше 50 баллов

5. Правда ли, что количество посещаемых занятий с репетитором в месяц напрямую влияет на балл в конечном экзамене?

6. Как физическая активность влияет на успеваемость?

7. Постройте HeatMap где ось Х - процент посещаемость, Y - количество занятий с репетитором, а Z - балл за итоговый экзамен*

\* Задание на доп. балл